# Generated by Django 4.0.3 on 2022-05-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='souscription',
            field=models.ManyToManyField(related_name='souscrir_training', to='compte.formation'),
        ),
    ]
