# Generated by Django 4.0.3 on 2022-05-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organisme_formation',
        ),
        migrations.AddField(
            model_name='user',
            name='organisme_formation',
            field=models.ManyToManyField(to='compte.organismeformation'),
        ),
    ]
