# Generated by Django 4.0.3 on 2022-05-18 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='souscrir',
            name='organisme_sous',
        ),
    ]
