# Generated by Django 4.0.3 on 2022-05-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organismeformation',
            old_name='password',
            new_name='password_connexion',
        ),
        migrations.AddField(
            model_name='organismeformation',
            name='password_messagerie',
            field=models.CharField(default='password', max_length=30),
        ),
    ]
