# Generated by Django 3.2.13 on 2022-04-19 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='appartenir',
            field=models.ManyToManyField(null=True, related_name='appartenir_content_type', to='compte.Organisme'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organisme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_content_type', to='compte.organisme'),
        ),
        migrations.AlterField(
            model_name='user',
            name='provenir',
            field=models.ManyToManyField(null=True, related_name='provenir_content_type', to='compte.Organisme'),
        ),
    ]
