# Generated by Django 4.0.3 on 2022-06-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='path',
            field=models.FileField(upload_to='doc_generate/'),
        ),
    ]
