# Generated by Django 4.0.3 on 2022-05-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organismeformation',
            name='password_connexion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organismeformation',
            name='password_messagerie',
            field=models.CharField(max_length=100),
        ),
    ]
