# Generated by Django 4.0.3 on 2022-06-02 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='souscrir',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='souscrir',
            name='objectifs_formation',
        ),
        migrations.RemoveField(
            model_name='souscrir',
            name='programme_formation',
        ),
    ]
