# Generated by Django 4.0.3 on 2022-05-09 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organismeformation',
            old_name='phone_number',
            new_name='company_phone_number',
        ),
        migrations.RenameField(
            model_name='societeformation',
            old_name='phone_number',
            new_name='company_phone_number',
        ),
    ]
