# Generated by Django 4.0.3 on 2022-05-11 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='appartenir',
            new_name='appartenir_other_user',
        ),
        migrations.AddField(
            model_name='user',
            name='appartenir_stagiaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_stagiare_appt_type', to='compte.organismeformation'),
        ),
    ]
