# Generated by Django 4.0.3 on 2022-06-03 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organismeformation',
            name='connected',
        ),
    ]
