# Generated by Django 4.0.3 on 2022-06-20 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='assister',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assister_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='path',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='concerner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='concerner_courses', to='compte.courses'),
        ),
    ]
