# Generated by Django 4.0.3 on 2022-05-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organisme_formation',
            field=models.ManyToManyField(null=True, related_name='organisme', to='compte.organismeformation'),
        ),
    ]
