# Generated by Django 4.0.3 on 2022-05-20 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='etablir',
        ),
    ]
