# Generated by Django 4.0.3 on 2022-05-12 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='societe',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='societe_admin_type', to='compte.societeformation'),
        ),
    ]
