# Generated by Django 3.2.13 on 2022-04-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_alter_user_organisme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisme',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin_simple',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_client',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_formateur',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_planificateur',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_sup_planificateur',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisme',
            name='company_stamp',
            field=models.FileField(null=True, upload_to='company_stamp/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cv',
            field=models.FileField(null=True, upload_to='cv/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
