# Generated by Django 4.0.3 on 2022-06-08 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_alter_reservation_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='assister',
        ),
        migrations.AddField(
            model_name='courses',
            name='assister',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assister_content_type', to=settings.AUTH_USER_MODEL),
        ),
    ]
