# Generated by Django 3.2.13 on 2022-04-25 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_user_is_admin_org'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin_org',
            new_name='is_autorise',
        ),
    ]
