# Generated by Django 4.0.3 on 2022-05-13 04:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_alter_user_societe'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Rp_Stagiaire',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
