# Generated by Django 4.0.3 on 2022-05-30 05:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_alter_user_organisme_formation'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('intitule', models.CharField(max_length=100)),
                ('objectif', models.TextField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('competence_atteste', models.CharField(max_length=100)),
                ('modalite_evaluation', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='formation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='programme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('intitule', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('attribue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compte.certificate')),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='allouer',
            field=models.ManyToManyField(to='compte.formation'),
        ),
    ]
