# Generated by Django 4.0.3 on 2022-05-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_user_souscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='souscription',
        ),
    ]
