# Generated by Django 4.0.3 on 2022-06-02 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_remove_souscrir_certification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souscrir',
            name='stagiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souscrirs', to=settings.AUTH_USER_MODEL),
        ),
    ]
