# Generated by Django 4.0.3 on 2022-06-07 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0003_rename_intitule_programme_libelle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reserver',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='proposer',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposer_content_type', to=settings.AUTH_USER_MODEL),
        ),
    ]
