# Generated by Django 4.0.3 on 2022-05-30 09:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0003_certificate_alter_formation_id_programme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='allouer',
        ),
        migrations.CreateModel(
            name='allouer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compte.certificate')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compte.formation')),
            ],
        ),
    ]
