# Generated by Django 4.0.3 on 2022-05-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0003_user_rp_stagiaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dispenser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='competence',
        ),
        migrations.AddField(
            model_name='user',
            name='competence',
            field=models.ManyToManyField(related_name='dispenser_content_type', to='compte.formation'),
        ),
    ]
