# Generated by Django 4.0.3 on 2022-06-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0004_alter_generatedocument_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedocument',
            name='path',
            field=models.FileField(default='compte.views.CreateDocumentsStagiaire.my_canvas', upload_to='doc_generate/'),
        ),
    ]
