# Generated by Django 4.0.3 on 2022-05-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0004_remove_certificate_allouer_allouer'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='allouer',
            field=models.ManyToManyField(to='compte.formation'),
        ),
        migrations.DeleteModel(
            name='allouer',
        ),
    ]
