# Generated by Django 4.0.3 on 2022-06-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0005_alter_generatedocument_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedocument',
            name='path',
            field=models.FileField(default='None', upload_to='doc_generate/'),
        ),
    ]
